import './index.css'
const Partners =()=>{
    return(
        

        
        <div id='partners' className='partners'>  
            <h1>PARTNERSHIP</h1> 
        <div className='mainimages'>
           <div className='images'>
            <img src='/media/Rotary.jpg' alt='rotary' className='rotary'/>
            <img src='/media/village.png' alt='karen' className='karen'/>
            <img src='/media/page.png' alt='page' className='page'/>
           </div>
           <div className='organisation-info'>
           <p>We also partner with Mathew 25 Children's Home. The average cost to support one child is $4 per day. How we help them is by providing them with fitting  <br/>clothes and bedding. We also provide funds generated by resuing and recyling used textiles. The funds are used to strengthen and grow this home.</p>
        </div>
        </div>
        </div>
        
    )
}
export default Partners
